### ISSUE TITLE
What is the llvm version for zksolc?

### ISSUE THREAD

**Issue by hrshy0629** [matter-labs/era-compiler-solidity#6]
What is the llvm version for zksolc? I tried to convert the compiled ll files to bc files and use llvm pass to do the related operations. But when I used llvm-as to convert ll to bc files, it produced a type error. So what should I do?

`llvm-as: _home_sunhy_samrtCC_yulset_Ballot.yul.unoptimized.ll:11:32: error: expected type
@ptr_calldata = private global ptr addrspace(3) null`

Does this mean that we can't use llvm pass for this right now?

**Comment by hedgar2017** [comment]
Hey @hrshy0629, we are using LLVM 15.
You're probably using older version of LLVM which doesn't support opaque pointers.
Could you provide more information about the toolchain you're using?

**Comment by hrshy0629** [comment]
In fact, I have completed llvm-as for LLVM 15.04 to correct `ll` files to `bc` files. However, I noticed that the `ll` file did not generate data with some key information, such as function line numbers and variables in the yul file. I'm curious, is this something that requires specific instructions, or is it something that hasn't been done yet? Because I need some key information to analyze the function calls in the `ll` file.

**Comment by hrshy0629** [comment]
In addition, I have noticed a number of other functions appearing in the `yul` file. Are these all `solc` generic functions? What role do they play in generating `ll` files?

**Comment by hedgar2017** [comment]
> In addition, I have noticed a number of other functions appearing in the `yul` file. Are these all `solc` generic functions? What role do they play in generating `ll` files?

What other functions are those exactly?

**Comment by hrshy0629** [comment]
In the diagram below, one is the original contract and the other is the corresponding yul file, but it is clear that there are many functions that did not exist in the original contract. In fact, I tried to use llvm to optimize the contract, but I found that these functions are automatically generated, especially the corresponding ll files are automatically generated from yul files, which makes the LLVM IR quite complicated. How did you optimize ll files? Why are there both optimized and unoptimized ll files in the ll file generated by yul? what's more, an optimized ll file appears with a unreachable instruction that seems to abort some code?
![合约函数图片](https://github.com/matter-labs/era-compiler-solidity/assets/25855706/db42071b-1c21-48fd-ba7f-7d5651aac0e3)
![合约函数图片2](https://github.com/matter-labs/era-compiler-solidity/assets/25855706/1bad8836-c107-4eda-b6ab-d5db236d5ae1)

**Comment by hedgar2017** [comment]
1. The Yul functions you mentioned are generated by the solc compiler, not ours.
2. We translate Yul into our subset of LLVM IR, adding a lot of boilerplate required for our zkEVM runtime. The Yul helper functions must be optimized out or inlined unless you deliberately disable the LLVM optimizer.
3. There is little you can optimize. The LLVM IR is already optimized for zkEVM. There are a few passes like machine outliner incoming soon, but they are mostly on MIR level rather than LLVM IR.
4. You can run zksolc with `--debug-output-dir` option, which will output all IRs into the folder you specify, including optimized and unoptimized LLVM IR.

**Comment by hrshy0629** [comment]
[cons.zip](https://github.com/matter-labs/era-compiler-solidity/files/11714047/cons.zip)

In fact, we want to automate vulnerability detection of contracts through the processing of LLVM IR. The compressed package contains the reentrant attack sample generated by chatGPT. But I find that even the same function has different IR in different calls, which makes me confused, shouldn't the IR of the same function be the same?   The function withdraw are fidderent in different `ll` files.

**Comment by hedgar2017** [comment]
@hrshy0629 I may not be following everything, but LLVM IR doesn't correspond directly to the Solidity code.
It is generated from Yul, which is generated from Solidity by solc and then optimized before it is received by zksolc.

Regarding the `withdraw` function, it's only present in one of the LLVM IR files which corresponds to `Wallet.sol`. It's called `external_fun_withdraw_55` alike to Yul, since our unoptimized LLVM IR is very close to Yul we receive from solc, meaning some boilerplate is added, but no generic optimizations applied.
